--
-- Script was generated by Devart dbForge Studio 2021 for SQL Server, Version 6.0.383.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 17/04/2022 18:46:06
-- Server version: 15.00.2070
--

CREATE DATABASE DYNAMICS
GO

USE DYNAMICS
GO

IF DB_NAME() <> N'DYNAMICS' SET NOEXEC ON
GO

--
-- Create table [dbo].[Venda]
--
PRINT (N'Create table [dbo].[Venda]')
GO
CREATE TABLE dbo.Venda (
  Id smallint IDENTITY,
  Data datetime NOT NULL,
  PrecoTotal decimal(18, 2) NOT NULL,
  Desconto decimal(18, 2) NULL DEFAULT (0),
  NF varchar(max) NULL,
  CONSTRAINT PK_Venda_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[TipoPromocao]
--
PRINT (N'Create table [dbo].[TipoPromocao]')
GO
CREATE TABLE dbo.TipoPromocao (
  Id smallint IDENTITY,
  Descricao varchar(50) NOT NULL,
  CONSTRAINT PK_TipoPromocao_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO
INSERT INTO TipoPromocao(Descricao) VALUES ('QUANTIDADE MÍNIMA'), ('QUANTIDADE BÔNUS'), ('DESCRICAO');

--
-- Create table [dbo].[Promocao]
--
PRINT (N'Create table [dbo].[Promocao]')
GO
CREATE TABLE dbo.Promocao (
  Id smallint IDENTITY,
  Descricao varchar(50) NULL,
  Desconto decimal(18, 2) NULL,
  DataInicio date NOT NULL,
  DataFim date NOT NULL,
  QtdeMin int NULL,
  QtdeBonus int NULL,
  Ativo bit NOT NULL DEFAULT (1),
  IdTipoPromocao smallint NULL,
  CONSTRAINT PK_Promocao_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create foreign key [FK_ID_PROMOCAO_TIPOPROMOCAO] on table [dbo].[Promocao]
--
PRINT (N'Create foreign key [FK_ID_PROMOCAO_TIPOPROMOCAO] on table [dbo].[Promocao]')
GO
ALTER TABLE dbo.Promocao
  ADD CONSTRAINT FK_ID_PROMOCAO_TIPOPROMOCAO FOREIGN KEY (IdTipoPromocao) REFERENCES dbo.TipoPromocao (Id)
GO

--
-- Create table [dbo].[Categoria]
--
PRINT (N'Create table [dbo].[Categoria]')
GO
CREATE TABLE dbo.Categoria (
  Id smallint IDENTITY,
  Descricao varchar(50) NOT NULL,
  IdPromocao smallint NULL,
  CONSTRAINT PK_Categoria_ID PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create foreign key [FK_CATEGORIA_ID_PROMOCAO] on table [dbo].[Categoria]
--
PRINT (N'Create foreign key [FK_CATEGORIA_ID_PROMOCAO] on table [dbo].[Categoria]')
GO
ALTER TABLE dbo.Categoria
  ADD CONSTRAINT FK_CATEGORIA_ID_PROMOCAO FOREIGN KEY (IdPromocao) REFERENCES dbo.Promocao (Id)
GO

--
-- Create table [dbo].[Produto]
--
PRINT (N'Create table [dbo].[Produto]')
GO
CREATE TABLE dbo.Produto (
  Id smallint IDENTITY,
  Nome varchar(50) NULL,
  Preco decimal(18, 2) NULL DEFAULT (0),
  IdCategoria smallint NOT NULL,
  CONSTRAINT PK_Produto_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create foreign key [FK_ID_PRODUTO_CATEGORIA] on table [dbo].[Produto]
--
PRINT (N'Create foreign key [FK_ID_PRODUTO_CATEGORIA] on table [dbo].[Produto]')
GO
ALTER TABLE dbo.Produto
  ADD CONSTRAINT FK_ID_PRODUTO_CATEGORIA FOREIGN KEY (IdCategoria) REFERENCES dbo.Categoria (Id)
GO

--
-- Create table [dbo].[ProdutoPromocao]
--
PRINT (N'Create table [dbo].[ProdutoPromocao]')
GO
CREATE TABLE dbo.ProdutoPromocao (
  IdProduto smallint NOT NULL,
  IdPromocao smallint NOT NULL,
  CONSTRAINT PK_ProdutoPromocao PRIMARY KEY CLUSTERED (IdProduto, IdPromocao)
)
ON [PRIMARY]
GO

--
-- Create foreign key [FK_ID_PRODUTOPROMO_PRODUTO] on table [dbo].[ProdutoPromocao]
--
PRINT (N'Create foreign key [FK_ID_PRODUTOPROMO_PRODUTO] on table [dbo].[ProdutoPromocao]')
GO
ALTER TABLE dbo.ProdutoPromocao
  ADD CONSTRAINT FK_ID_PRODUTOPROMO_PRODUTO FOREIGN KEY (IdProduto) REFERENCES dbo.Produto (Id)
GO

--
-- Create foreign key [FK_ID_PRODUTOPROMO_PROMOCAO] on table [dbo].[ProdutoPromocao]
--
PRINT (N'Create foreign key [FK_ID_PRODUTOPROMO_PROMOCAO] on table [dbo].[ProdutoPromocao]')
GO
ALTER TABLE dbo.ProdutoPromocao
  ADD CONSTRAINT FK_ID_PRODUTOPROMO_PROMOCAO FOREIGN KEY (IdPromocao) REFERENCES dbo.Promocao (Id)
GO

--
-- Create user [dynamics]
--
PRINT (N'Create user [dynamics]')
GO
CREATE USER dynamics
  FOR LOGIN dynamics
GO

--
-- Create table [dbo].[Item]
--
PRINT (N'Create table [dbo].[Item]')
GO
CREATE TABLE dbo.Item (
  IdProduto smallint IDENTITY,
  IdVenda smallint NOT NULL,
  Qtde int NULL,
  Desconto decimal(18, 2) NULL,
  CONSTRAINT PK_Item_Id PRIMARY KEY CLUSTERED (IdProduto, IdVenda)
)
ON [PRIMARY]
GO

--
-- Create sequence [dbo].[hibernate_sequence]
--
PRINT (N'Create sequence [dbo].[hibernate_sequence]')
GO
CREATE SEQUENCE dbo.hibernate_sequence
  AS bigint
  START WITH 1
  INCREMENT BY 1
  NO CYCLE
  CACHE 
GO
SET NOEXEC OFF
GO